use master;
DROP DATABASE IdentityDB;
CREATE DATABASE IdentityDB;
USE IdentityDB;


CREATE TABLE USERS (
  id INT IDENTITY(1,1) PRIMARY KEY,
  username NVARCHAR(50) NOT NULL UNIQUE,
  password NVARCHAR(255) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
GO